### ISSUE TITLE
按照指示，无法配置好环境

### ISSUE THREAD

**Issue by 13012473536** [DataCanvasIO/HyperTS#109]
作者您好，我分别使用了requirements.txt和您在其它issues贴出的环境包列表，但仍无法正常跑通深度学习模式。例如当前的情况，我的环境列表为follow您在其它issues贴出的列表，仅在安装报错时做调整。报错为：

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ajj6jolh/numba_3c53dd7cfefa4a56983a902eed128b55/setup.py", line 15, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

我的环境包列表为：
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.2.1
attrs==21.2.0
ax-platform==0.2.2
backcall==0.2.0
bcrypt==4.0.1
beautifulsoup4==4.11.1
bleach==5.0.1
botorch==0.5.1
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
click==8.1.3
cloudpickle==2.2.1
contourpy==1.0.7
convertdate
cryptography==39.0.0
cycler==0.11.0
Cython==0.29.17
dask==2023.1.1
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
distributed==2023.1.1
ephem==4.1.4
executing==1.2.0
fastjsonschema==2.16.1
featuretools
filterpy==1.4.5
fonttools==4.38.0
fsspec==2023.1.0
HeapDict==1.0.1
hijri-converter==2.2.4
holidays==0.18
htmlmin==0.1.12
hypernets
hyperts==0.2.0
idna==3.4
ImageHash==4.2.1
importlib-metadata
importlib-resources==5.10.2
ipython==8.9.0
ipython-genutils==0.2.0
ipywidgets==7.7.1
jedi==0.18.2
Jinja2==3.1.2
joblib
jsonschema==4.9.0
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.1
kiwisolver==1.4.4
korean-lunar-calendar==0.3.1
lightgbm==3.3.5
llvmlite==0.39.1
locket==1.0.0
LunarCalendar==0.0.9
MarkupSafe==2.1.2
matplotlib==3.5.3
matplotlib-inline==0.1.6
missingno==0.5.1
mistune==0.8.4
msgpack==1.0.4
multimethod==1.8
nbclient==0.6.6
nbconvert==6.5.0
nbformat==5.4.0
numba
numpy==1.17.3
packaging==23.0
pandas==1.3.5
pandas-profiling==3.2.0
pandocfilters==1.5.0
paramiko==3.0.0
parso==0.8.3
partd==1.3.0
patsy
pexpect==4.8.0
phik
pickleshare==0.7.5
Pillow==9.4.0
pip==22.3.1
pkgutil_resolve_name==1.3.10
prettytable==3.6.0
prometheus-client==0.14.1
prompt-toolkit==3.0.36
prophet==1.1.2
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==11.0.0
pycparser==2.21
pydantic==1.9.1
Pygments==2.14.0
pymannkendall==1.4.2
PyMeeus==0.5.12
PyNaCl==1.5.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2022.7.1
PyWavelets==1.3.0
PyYAML==6.0
requests==2.28.2
scikit-learn==1.2.1
scipy==1.7.3
seaborn==0.11.2
Send2Trash==1.8.0
setuptools==66.1.1
six==1.16.0
sktime
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
stack-data==0.6.2
statsmodels==0.13.5
tangled-up-in-unicode==0.2.0
tblib==1.7.0
terminado==0.15.0
threadpoolctl==3.1.0
tinycss2==1.1.1
toolz==0.12.0
tornado==6.2
tqdm==4.64.1
traitlets==5.8.1
urllib3==1.26.14
visions==0.7.4
wcwidth==0.2.6
webencodings==0.5.1
wheel==0.38.4
widgetsnbextension==3.6.1
woodwork
wrapt==1.14.1
XlsxWriter==3.0.7
zict==2.2.0
zipp==3.12.0
cmdstanpy

在1080ti,2080ti,v100,三种型号上安装均是环境无法匹配。
谢谢作者的阅览！麻烦给些指导

**Comment by 13012473536** [comment]
已解决。用高版本tf2.9就能兼容这些环境包。
i fix it with tf2.9, cuda11. Then these pip packages will not be conflicted.
