### ISSUE TITLE
how to use mode 'dl'?

### ISSUE THREAD

**Issue by jelly909** [DataCanvasIO/HyperTS#50]
The code I use is as follows：
![1659581964728](https://user-images.githubusercontent.com/55540371/182753600-8797dc0e-3e2c-4d27-bd6d-ca1082adc9df.jpg)

An error is as follows：
08-04 10:57:12 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 1 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'HybirdRNNWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 677, in _build_estimator
    rnn = HybirdRNNWrapper(fit_kwargs, **kwargs)
NameError: name 'HybirdRNNWrapper' is not defined
**************************************************
08-04 10:57:13 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 2 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'HybirdRNNWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 677, in _build_estimator
    rnn = HybirdRNNWrapper(fit_kwargs, **kwargs)
NameError: name 'HybirdRNNWrapper' is not defined
**************************************************
08-04 10:57:13 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 3 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'NBeatsWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 1030, in _build_estimator
    nbeats = NBeatsWrapper(fit_kwargs, **kwargs)
NameError: name 'NBeatsWrapper' is not defined
**************************************************
08-04 10:57:14 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 4 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'LSTNetWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 866, in _build_estimator
    lstnet = LSTNetWrapper(fit_kwargs, **kwargs)
NameError: name 'LSTNetWrapper' is not defined
**************************************************
08-04 10:57:14 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 5 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'NBeatsWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 1030, in _build_estimator
    nbeats = NBeatsWrapper(fit_kwargs, **kwargs)
NameError: name 'NBeatsWrapper' is not defined
**************************************************
08-04 10:57:15 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 6 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'HybirdRNNWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 677, in _build_estimator
    rnn = HybirdRNNWrapper(fit_kwargs, **kwargs)
NameError: name 'HybirdRNNWrapper' is not defined
**************************************************
08-04 10:57:16 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 7 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'DeepARWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 518, in _build_estimator
    deepar = DeepARWrapper(fit_kwargs, **kwargs)
NameError: name 'DeepARWrapper' is not defined
**************************************************
08-04 10:57:16 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 8 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'DeepARWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 518, in _build_estimator
    deepar = DeepARWrapper(fit_kwargs, **kwargs)
NameError: name 'DeepARWrapper' is not defined
**************************************************
08-04 10:57:17 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 9 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'LSTNetWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 866, in _build_estimator
    lstnet = LSTNetWrapper(fit_kwargs, **kwargs)
NameError: name 'LSTNetWrapper' is not defined
**************************************************
08-04 10:57:17 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 10 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'DeepARWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 518, in _build_estimator
    deepar = DeepARWrapper(fit_kwargs, **kwargs)
NameError: name 'DeepARWrapper' is not defined
**************************************************
08-04 10:57:18 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 11 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'DeepARWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 518, in _build_estimator
    deepar = DeepARWrapper(fit_kwargs, **kwargs)
NameError: name 'DeepARWrapper' is not defined
**************************************************
08-04 10:57:18 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 12 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'DeepARWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 518, in _build_estimator
    deepar = DeepARWrapper(fit_kwargs, **kwargs)
NameError: name 'DeepARWrapper' is not defined
**************************************************
08-04 10:57:19 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 13 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'HybirdRNNWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 677, in _build_estimator
    rnn = HybirdRNNWrapper(fit_kwargs, **kwargs)
NameError: name 'HybirdRNNWrapper' is not defined
**************************************************
08-04 10:57:20 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 14 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'NBeatsWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 1030, in _build_estimator
    nbeats = NBeatsWrapper(fit_kwargs, **kwargs)
NameError: name 'NBeatsWrapper' is not defined
**************************************************
08-04 10:57:20 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 15 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'LSTNetWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 866, in _build_estimator
    lstnet = LSTNetWrapper(fit_kwargs, **kwargs)
NameError: name 'LSTNetWrapper' is not defined
**************************************************
08-04 10:57:21 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 16 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'LSTNetWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 866, in _build_estimator
    lstnet = LSTNetWrapper(fit_kwargs, **kwargs)
NameError: name 'LSTNetWrapper' is not defined
**************************************************
08-04 10:57:21 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 17 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'DeepARWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 518, in _build_estimator
    deepar = DeepARWrapper(fit_kwargs, **kwargs)
NameError: name 'DeepARWrapper' is not defined
**************************************************
08-04 10:57:22 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 18 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'NBeatsWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 1030, in _build_estimator
    nbeats = NBeatsWrapper(fit_kwargs, **kwargs)
NameError: name 'NBeatsWrapper' is not defined
**************************************************
08-04 10:57:23 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 19 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'DeepARWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 518, in _build_estimator
    deepar = DeepARWrapper(fit_kwargs, **kwargs)
NameError: name 'DeepARWrapper' is not defined
**************************************************
08-04 10:57:23 E hypernets.d.in_process_dispatcher.py 90 - >>>>>>>>>>>>>>>>>>>> Trial 20 failed! <<<<<<<<<<<<<<<<<<<<
NameError: name 'LSTNetWrapper' is not defined
Traceback (most recent call last):
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\dispatchers\in_process_dispatcher.py", line 62, in dispatch
    trial = hyper_model._run_trial(space_sample, trial_no, X, y, X_eval, y_eval, cv, num_folds, model_file,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hypernets\model\hyper_model.py", line 49, in _run_trial
    estimator = self._get_estimator(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 469, in _get_estimator
    estimator = HyperTSEstimator(task=self.task,
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 58, in __init__
    self._build_model(space_sample)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\hyper_ts.py", line 67, in _build_model
    outputs[0].build_estimator(self.task)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 42, in build_estimator
    self.estimator = self._build_estimator(task, self.fit_kwargs, pv)
  File "F:\anaconda\envs\hyperts\lib\site-packages\hyperts\framework\estimators.py", line 866, in _build_estimator
    lstnet = LSTNetWrapper(fit_kwargs, **kwargs)
NameError: name 'LSTNetWrapper' is not defined
**************************************************

**Comment by zhangxjohn** [comment]
Have you installed TensorFlow?

**Comment by jelly909** [comment]
Solved, I forgot to restart TensorFlow after installing it. Thanks a lot!
