### ISSUE TITLE
TypeError: X is not of a supported input data type

### ISSUE THREAD

**Issue by cryptocoinserver** [DataCanvasIO/HyperTS#59]
```
10-01 16:48:13 I hyperts.hyper_ts.py 244 - estimator is transforming the train set

10-01 16:48:14 E hypernets.m.hyper_model.py 83 - run_trail failed! trail_no=3
10-01 16:48:14 E hypernets.m.hyper_model.py 85 - Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hypernets/model/hyper_model.py", line 78, in _run_trial
    estimator.fit(X, y, **fit_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hyperts/hyper_ts.py", line 255, in fit
    self.model.fit(X_transformed, y, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hyperts/framework/wrappers/stats_wrappers.py", line 209, in fit
    self.model.fit(X, y)
  File "/usr/local/lib/python3.7/dist-packages/sktime/classification/base.py", line 156, in fit
    X_metadata = self._check_classifier_input(X, y)
  File "/usr/local/lib/python3.7/dist-packages/sktime/classification/base.py", line 699, in _check_classifier_input
    f"X is not of a supported input data type."
TypeError: X is not of a supported input data type.X must be in a supported mtype format for Panel, found <class 'pandas.core.frame.DataFrame'>Use datatypes.check_is_mtype to check conformance with specifications.

```
Can you help with this error?

**Comment by zhangxjohn** [comment]
Could you please elaborate on your task, data format and initialization parameter settings?
