### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Timedelta' and 'float'

### ISSUE THREAD

**Issue by cryptocoinserver** [DataCanvasIO/HyperTS#60]
```
10-01 19:18:03 I hyperts.hyper_ts.py 244 - estimator is transforming the train set

10-01 19:18:04 E hypernets.m.hyper_model.py 83 - run_trail failed! trail_no=3
10-01 19:18:04 E hypernets.m.hyper_model.py 85 - Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hypernets/model/hyper_model.py", line 78, in _run_trial
    estimator.fit(X, y, **fit_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hyperts/hyper_ts.py", line 255, in fit
    self.model.fit(X_transformed, y, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hyperts/framework/wrappers/dl_wrappers.py", line 108, in fit
    X = self.fit_transform(X)
  File "/usr/local/lib/python3.7/dist-packages/hyperts/framework/wrappers/_base.py", line 135, in fit_transform
    transform_X = self.transformers.fit_transform(X)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 426, in fit_transform
    Xt = self._fit(X, y, **fit_params_steps)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 355, in _fit
    **fit_params_steps[name],
  File "/usr/local/lib/python3.7/dist-packages/joblib/memory.py", line 352, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/base.py", line 852, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python3.7/dist-packages/hyperts/utils/transformers.py", line 207, in transform
    transform_X = (X - self.min) / (self.max - self.min + self.eps)
TypeError: unsupported operand type(s) for +: 'Timedelta' and 'float'

```
I think I figured the first error out. I set the mode to "dl".
Now I get the above error though.

**Comment by zhangxjohn** [comment]
Could you please elaborate on your task, data format and initialization parameter settings?

**Comment by zhangxjohn** [comment]
From the error, it looks there is a problem with your data format.
