### ISSUE TITLE
None: marshal data too short

### ISSUE THREAD

**Issue by benpaobamingliang1** [DataCanvasIO/HyperTS#66]
Model: "DeepAR"
_____________________________________________________________________________
248/248 [==============================] - 50s 186ms/step - loss: 0.3978 - rmse: 0.9683 - val_loss: 0.4870 - val_rmse: 1.0712
11-01 11:08:17 E hypernets.e._experiment.py 106 - ExperimentID:[HyperTS_56148232a2a64822f2b6a0028102d580] - None: marshal data too short
Traceback (most recent call last):
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment\_experiment.py", line 91, in run
    y_eval=self.y_eval, **kwargs)
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment\compete.py", line 1551, in train
    raise e
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment\compete.py", line 1543, in train
    **kwargs)
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment\compete.py", line 1226, in fit_transform
    **kwargs)
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\framework\compete.py", line 287, in build_estimator
    estimators = [hyper_model.load_estimator(trial.model_file) for trial in trials]
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\framework\compete.py", line 287, in <listcomp>
    estimators = [hyper_model.load_estimator(trial.model_file) for trial in trials]
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\hyper_ts.py", line 478, in load_estimator
    return HyperTSEstimator._load(model_file, self.mode)
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\hyper_ts.py", line 398, in _load
    model = BaseDeepEstimator.load_model(model_file)
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\framework\dl\_base.py", line 864, in load_model
    model = load_model(h, custom_objects=custom_objects)
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\keras\utils\generic_utils.py", line 857, in func_load
    code = marshal.loads(raw_code)
EOFError: marshal data too short
请问为什么会出现这样的问题呢，我训练时会出现这样的报错

**Comment by zhangxjohn** [comment]
根据您所提供的信息，无法判断。请提供可以复现以上错误的更多信息。

**Comment by benpaobamingliang1** [comment]
好的，已QQ发您，谢谢您

**Comment by zhangxjohn** [comment]
遇到以上问题，建议检查tensorflow和numpy的版本兼容性问题。

**Comment by zhangxjohn** [comment]
遇到以上问题，建议检查tensorflow和numpy的版本兼容性问题。

**Comment by happysaten** [comment]
> Model: "DeepAR"
> 
> 248/248 [==============================] - 50s 186ms/step - loss: 0.3978 - rmse: 0.9683 - val_loss: 0.4870 - val_rmse: 1.0712 11-01 11:08:17 E hypernets.e._experiment.py 106 - ExperimentID:[HyperTS_56148232a2a64822f2b6a0028102d580] - None: marshal data too short Traceback (most recent call last): File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment_experiment.py", line 91, in run y_eval=self.y_eval, **kwargs) File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment\compete.py", line 1551, in train raise e File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment\compete.py", line 1543, in train **kwargs) File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hypernets\experiment\compete.py", line 1226, in fit_transform **kwargs) File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\framework\compete.py", line 287, in build_estimator estimators = [hyper_model.load_estimator(trial.model_file) for trial in trials] File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\framework\compete.py", line 287, in estimators = [hyper_model.load_estimator(trial.model_file) for trial in trials] File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\hyper_ts.py", line 478, in load_estimator return HyperTSEstimator._load(model_file, self.mode) File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\hyper_ts.py", line 398, in _load model = BaseDeepEstimator.load_model(model_file) File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\hyperts\framework\dl_base.py", line 864, in load_model model = load_model(h, custom_objects=custom_objects) File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler raise e.with_traceback(filtered_tb) from None File "D:\Program-SetUp\Anaconda\envs\TF2.3\lib\site-packages\keras\utils\generic_utils.py", line 857, in func_load code = marshal.loads(raw_code) EOFError: marshal data too short 请问为什么会出现这样的问题呢，我训练时会出现这样的报错

同样的问题，请问你解决了吗？我的python版本是3.8，tensorflow版本是2.10.1，numpy是1.2.1

**Comment by zhangxjohn** [comment]
感谢提问！

CSDN有这么解决的：https://blog.csdn.net/weixin_41930058/article/details/124276016

这个错误以前的检查点判断，你的np和tf的版本大概率不匹配，tf现在的更新有些不管np。

我这边使用tf=0.2.4和np=1.19.5没有这种问题。你可以尝试更新一下。
