### ISSUE TITLE
时序预测模型训练问题

### ISSUE THREAD

**Issue by jelly909** [DataCanvasIO/HyperTS#80]
报错如下：出现这种问题应该咋解决啊
02-21 06:17:11 E hypernets.m.hyper_model.py 83 - run_trail failed! trail_no=3
02-21 06:17:11 E hypernets.m.hyper_model.py 85 - Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/hyperts/framework/wrappers/stats_wrappers.py", line 108, in fit
    self.model = model.fit(disp=False, **self.init_kwargs)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 709, in fit
    skip_hessian=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/base/model.py", line 571, in fit
    full_output=full_output)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 244, in _fit
    hess=hessian)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 654, in _fit_lbfgs
    **extra_kwargs)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 198, in fmin_l_bfgs_b
    **opts)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 360, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 267, in fun_and_grad
    self._update_fun()
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 233, in _update_fun
    self._update_fun_impl()
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/base/model.py", line 531, in f
    return -self.loglike(params, *args) / nobs
  File "/usr/local/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 939, in loglike
    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 983, in loglike
    kfilter = self._filter(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 903, in _filter
    self._initialize_state(prefix=prefix, complex_step=complex_step)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/tsa/statespace/representation.py", line 984, in _initialize_state
    complex_step=complex_step)
  File "statsmodels/tsa/statespace/_representation.pyx", line 1373, in statsmodels.tsa.statespace._representation.dStatespace.initialize
  File "statsmodels/tsa/statespace/_representation.pyx", line 1362, in statsmodels.tsa.statespace._representation.dStatespace.initialize
  File "statsmodels/tsa/statespace/_initialization.pyx", line 288, in statsmodels.tsa.statespace._initialization.dInitialization.initialize
  File "statsmodels/tsa/statespace/_initialization.pyx", line 406, in statsmodels.tsa.statespace._initialization.dInitialization.initialize_stationary_stationary_cov
  File "statsmodels/tsa/statespace/_tools.pyx", line 1284, in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov
numpy.linalg.LinAlgError: Schur decomposition solver error.

**Comment by jelly909** [comment]
同一组数据，有时候报这个错，有时候又正常；

**Comment by zhangxjohn** [comment]
根据错误来看，怀疑你的statsmodels版本可能出现冲突了，可以降级试试，例如`0.12.1`。

**Comment by jelly909** [comment]
> 根据错误来看，怀疑你的statsmodels版本可能出现冲突了，可以降级试试，例如`0.12.1`。

好的！我去试试！
