### ISSUE TITLE
回归预测失败

### ISSUE THREAD

**Issue by wangjianqiao111** [DataCanvasIO/HyperTS#90]
你好，我在做回归任务时，模型训练完成后对训练集进行预测时报以下错误，麻烦帮忙看下是什么问题
2023-04-06 16:47:38.257 [ERROR] Traceback (most recent call last):
2023-04-06 16:47:38.257 [ERROR]   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2023-04-06 16:47:38.257 [ERROR]     "__main__", mod_spec)
2023-04-06 16:47:38.257 [ERROR]   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
2023-04-06 16:47:38.257 [ERROR]     exec(code, run_globals)
2023-04-06 16:47:38.257 [ERROR]   File "/opt/pylib/dc_runtime.zip/datacanvas/shell.py", line 134, in <module>
2023-04-06 16:47:38.258 [ERROR]   File "/opt/pylib/dc_runtime.zip/datacanvas/shell.py", line 120, in <module>
2023-04-06 16:47:38.258 [ERROR]   File "/opt/pylib/dc_runtime.zip/datacanvas/shell.py", line 29, in get_args_func
2023-04-06 16:47:38.258 [ERROR]   File "/opt/pylib/dc_runtime.zip/datacanvas/shell.py", line 61, in _execfile
2023-04-06 16:47:38.258 [ERROR]   File "main.py", line 45, in <module>
2023-04-06 16:47:38.259 [ERROR]     forecast = model.predict(df_new)
2023-04-06 16:47:38.259 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hyperts/framework/compete.py", line 536, in predict
2023-04-06 16:47:38.260 [ERROR]     y_pred = self.sk_pipeline.predict(X)
2023-04-06 16:47:38.260 [ERROR]   File "/usr/local/lib/python3.7/site-packages/sklearn/utils/metaestimators.py", line 119, in <lambda>
2023-04-06 16:47:38.260 [ERROR]     out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
2023-04-06 16:47:38.260 [ERROR]   File "/usr/local/lib/python3.7/site-packages/sklearn/pipeline.py", line 408, in predict
2023-04-06 16:47:38.260 [ERROR]     return self.steps[-1][-1].predict(Xt, **predict_params)
2023-04-06 16:47:38.260 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hyperts/utils/ensemble/_greedy.py", line 67, in predict
2023-04-06 16:47:38.260 [ERROR]     est_predictions = self._X2predictions(X)
2023-04-06 16:47:38.260 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hyperts/utils/ensemble/_greedy.py", line 139, in _X2predictions
2023-04-06 16:47:38.260 [ERROR]     pred = self._estimator_predict(estimator, X)
2023-04-06 16:47:38.260 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hypernets/tabular/ensemble/base_ensemble.py", line 34, in _estimator_predict
2023-04-06 16:47:38.260 [ERROR]     pred = estimator.predict(X)
2023-04-06 16:47:38.260 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hyperts/hyper_ts.py", line 300, in predict
2023-04-06 16:47:38.260 [ERROR]     preds = self.model.predict(X_transformed, **kwargs)
2023-04-06 16:47:38.260 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hyperts/framework/wrappers/dl_wrappers.py", line 83, in predict
2023-04-06 16:47:38.261 [ERROR]     X = self.transform(X)
2023-04-06 16:47:38.261 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hyperts/framework/wrappers/_base.py", line 166, in transform
2023-04-06 16:47:38.261 [ERROR]     X = tb.from_nested_df_to_3d_array(X)
2023-04-06 16:47:38.261 [ERROR]   File "/usr/local/lib/python3.7/site-packages/hyperts/utils/tstoolbox.py", line 545, in from_nested_df_to_3d_array
2023-04-06 16:47:38.261 [ERROR]     raise ValueError
2023-04-06 16:47:38.261 [ERROR] ValueError
2023-04-06 16:47:40.492 [ERROR] exit code is 1

**Comment by zhangxjohn** [comment]
你的数据定义可能存在问题，无法从`nested DataFame`转成`3D array`的形式，可以从`toolbox.py`调用`from_nested_df_to_3d_array`函数自测一下查找原因。

**Comment by wangjianqiao111** [comment]
回归任务的预测结果为什么是这样的：
[  5.6191498    7.23569518   7.92735136   6.96889669   6.33656013
2023-04-06 18:06:55.452 [INFO]    5.37992251   5.45399016   5.34192425   5.40060091   7.44965953
2023-04-06 18:06:55.452 [INFO]   10.96693653  12.3248781   13.02884626  14.45617509  11.02101266
2023-04-06 18:06:55.452 [INFO]    9.10442281   7.99758524   7.70621067  11.32062185  14.21717543
2023-04-06 18:06:55.452 [INFO]   18.1368506   22.53652585  30.62719184  29.20028633  30.91615433
2023-04-06 18:06:55.452 [INFO]   30.5234524   26.33733815  24.14380628  22.13217485  20.98701555
2023-04-06 18:06:55.452 [INFO]   23.58383614  26.8686828   30.35203094  39.98220349  42.43875599
2023-04-06 18:06:55.452 [INFO]   41.52651024  41.95603234  47.797445    41.19929391  42.24954343
2023-04-06 18:06:55.452 [INFO]   39.75738478  35.92768741  42.48867488  44.73698974  45.86823166
2023-04-06 18:06:55.452 [INFO]   53.30675328  63.539343    61.51045162  56.02531207  56.48954177
2023-04-06 18:06:55.452 [INFO]   47.25257433  46.55910111  47.89940334  40.01557327  46.1618985
2023-04-06 18:06:55.452 [INFO]   46.36946524  48.28348726  53.69685543  64.69240946  56.14837611
2023-04-06 18:06:55.452 [INFO]   60.04844714  63.29634983  55.59147698  59.00676769  63.52132428
2023-04-06 18:06:55.452 [INFO]   54.23106742  57.85729939  60.8241188   63.46333051  70.38278354
2023-04-06 18:06:55.452 [INFO]   76.20823813  64.26220847  73.16886461  82.56032503  70.24809838
2023-04-06 18:06:55.452 [INFO]   76.18200076  83.97590495  71.64174593  72.25866354  77.46890176
2023-04-06 18:06:55.452 [INFO]   80.64619518  88.7890364   91.77892233  84.62659169  91.9457872
2023-04-06 18:06:55.452 [INFO]   94.74295426  82.61248828  88.74452472  97.46316636  83.61233569
2023-04-06 18:06:55.452 [INFO]   86.65763558  89.22309113  96.04379261 102.11622191 104.23254324
2023-04-06 18:06:55.452 [INFO]  105.02138949 106.86494602 107.72604287 100.8605342  103.81352008
2023-04-06 18:06:55.452 [INFO]  108.50681425  98.57369793  97.44680095  99.72849358 105.24572898
2023-04-06 18:06:55.452 [INFO]  107.04132343 104.9651928  102.46367336 104.54314256 105.07843281
2023-04-06 18:06:55.452 [INFO]  105.42907906 108.08231998 110.84204388 103.60378886 103.21516431
2023-04-06 18:06:55.452 [INFO]  103.09318651 117.38693751 114.92028142 123.25804592 117.35686637
2023-04-06 18:06:55.452 [INFO]  124.84394909 120.21722675 122.92185617 124.42753769 123.32307626
2023-04-06 18:06:55.452 [INFO]  120.24192263 115.64329863 121.77150131 123.98579145 126.13509918
2023-04-06 18:06:55.452 [INFO]  124.70048619 129.48448897 130.35763026 129.30883838 129.8319564 ]
不应该只有一列target列吗
